public func fabUnitedStatesStreetTypeName() -> String {
    [
        "Avenue",
        "Bay",
        "Boulevard",
        "Circle",
        "Court",
        "Cove",
        "Drive",
        "Expressway",
        "Lane",
        "Parkway",
        "Place",
        "Road",
        "Row",
        "Street",
        "Way",
    ].randomElement()!
}
